Solo teardown
tahiry-dev/teardown-magazine pull request #1
Opened 2020-09-11 12:43 UTC by tahiry-dev

Send pull request for my teardown project

2020-09-11 21:41 UTC, Spayco requested changes
# Changes Requested 

Hello! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

* [ ] Pull Request has a meaningful title and a brief description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)) (add something like the steps section in your README.md)

- [ ] you have repetitive code in your CSS, decrease it by making one class for a particular property (eg. `.d-flex` for `display: flex;`) so you won't have to repeat it again


### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2020-09-11 21:41 UTC, Spayco commented on index.html
> +    </header>
- [ ] [Optional] use `nav` element with `ul`/`li` inside

2020-09-12 03:25 UTC, tahiry-dev commented
- I used Toggle Pesticide to help me divide the whole page into boxes.
- ”Translated” these boxes into empty HTML Containers
- Aligned these containers properly using Grid, Flexbox, and Float
- Gave general color to all of the boxes
- Reviewed the design principles
- Gave darker color to the most pleasant area of boxes

2020-09-12 05:22 UTC, Spayco approved these changes
# Project Approved ✔️ 

thank you for making the required changes, your project is now approved!

P.S: you can edit the very first post in your PR instead of posting a comment, please next time describes the project on the first post of the PR.

### please don't forget to merge to master, good luck with the next projects!


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2020-09-13 17:23 UTC, merged